### ISSUE TITLE
Share entire file if nothing is selected

### ISSUE THREAD

**Issue by kotx** [ProckerIO/CodeShare-VSCode-Extension#1]
Also handle API errors instead of giving the user an error dialog but then returning success & https://code.prkr.li/undefined

**Comment by niklas-stegmann** [comment]
Hey,

thank you for your issue. We have added this feature in release 1.0.7, which is now available on the marketplace.

Feel free to give us a rating on the vs code marketplace.

Thanks in advance & best regards,
Niklas
