### ISSUE TITLE
CodeShare's Broken. 

### ISSUE THREAD

**Issue by Dev5H0** [ProckerIO/CodeShare-VSCode-Extension#3]
Hello, now when pressing the CodeShare button , nothing happens. When you run it using the command palette, you get an error saying "Cannot read property 'statusCode' of undefined".

**Comment by niklas-stegmann** [comment]
Thank you for creating this issue.

A little late (sorry for that), but I've now fixed the bug and uploaded a new version to the marketplace.

Have a great Christmas time 🎄!
